# .github/workflows/pr-validation.yml
name: Pull Request Validation

on:
 pull_request:
  branches: [main]

jobs:
 pr-validation:
  name: PR Validation Pipeline
  runs-on: ubuntu-latest

  steps:
   # ─────────────────────────────────────────────────────────────────────────
   # Checkout
   # Retrieves the repository code.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Checkout repository
     uses: actions/checkout@v4

   # ─────────────────────────────────────────────────────────────────────────
   # Setup Environment
   # Installs Node.js and project dependencies.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Set up Node.js and enable npm cache
     uses: actions/setup-node@v4
     with:
      node-version-file: '.nvmrc'
      registry-url: 'https://registry.npmjs.org'
      cache: npm'

   - name: Install dependencies
     run: npm ci

   # ─────────────────────────────────────────────────────────────────────────
   # PR-Metadata Validation
   # Ensures branch naming and milestone conform to release flow.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Validate branch naming convention
     uses: amondnet/branch-name-validator@v2
     with:
      pattern: '^(release|hotfix)/v\\d+\\.\\d+\\.\\d+$'

   - name: Ensure PR has a valid milestone
     uses: actions-ecosystem/action-check-milestone@v1
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      pattern: '^v\\d+\\.\\d+\\.\\d+$'

   # ─────────────────────────────────────────────────────────────────────────
   # Quality Gates
   # Runs linters and formatting checks.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Lint JavaScript & TypeScript
     run: npm run lint:js

   - name: Lint CSS/SCSS
     run: npm run lint:css

   - name: Check code formatting
     run: npm run format:check

   # ─────────────────────────────────────────────────────────────────────────
   # Testing & Coverage
   # Executes unit tests and captures coverage report.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Run unit tests with coverage
     run: npm test

   - name: Upload coverage report
     uses: actions/upload-artifact@v3
     with:
      name: coverage-report
      path: coverage

   # ─────────────────────────────────────────────────────────────────────────
   # Build Verification
   # Verifies that distribution and documentation builds succeed.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Verify production distribution
     run: npm run dist

   - name: Build documentation
     run: npm run docs

   # ─────────────────────────────────────────────────────────────────────────
   # Security & Health
   # Audits dependencies, verifies licenses, and runs CodeQL analysis.
   # ─────────────────────────────────────────────────────────────────────────
   - name: Perform dependency audit
     run: npm audit --audit-level=high

   - name: Validate OSS licenses
     uses: cybercyclone/license-checker-action@v1
     with:
      allow: 'Apache-2.0,MIT'

   - name: Initialize CodeQL analysis
     uses: github/codeql-action/init@v2
     with:
      languages: javascript

   - name: Autobuild for CodeQL
     uses: github/codeql-action/autobuild@v2

   - name: Analyze code with CodeQL
     uses: github/codeql-action/analyze@v2
